// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DefaultDocumentDataSlicesSlice = TextContentSlice;

/**
 * Content for page documents
 */
interface DefaultDocumentData {
  /**
   * titre field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: titre de la page
   * - **API ID Path**: default.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: default.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DefaultDocumentDataSlicesSlice>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `default`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DefaultDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DefaultDocumentData>,
    "default",
    Lang
  >;

export type AllDocumentTypes = DefaultDocument;

/**
 * Primary content in *TextContent → Default → Primary*
 */
export interface TextContentSliceDefaultPrimary {
  /**
   * corps de texte field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: lorem…
   * - **API ID Path**: text_content.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for TextContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextContent → blockContent → Primary*
 */
export interface TextContentSliceBlockContentPrimary {
  /**
   * list de films field in *TextContent → blockContent → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.blockContent.primary.filmList
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  filmList: prismic.SelectField<"séniors" | "juniors">;
}

/**
 * blockContent variation for TextContent Slice
 *
 * - **API ID**: `blockContent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSliceBlockContent = prismic.SharedSliceVariation<
  "blockContent",
  Simplify<TextContentSliceBlockContentPrimary>,
  never
>;

/**
 * Slice variation for *TextContent*
 */
type TextContentSliceVariation =
  | TextContentSliceDefault
  | TextContentSliceBlockContent;

/**
 * TextContent Shared Slice
 *
 * - **API ID**: `text_content`
 * - **Description**: TextContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSlice = prismic.SharedSlice<
  "text_content",
  TextContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DefaultDocument,
      DefaultDocumentData,
      DefaultDocumentDataSlicesSlice,
      AllDocumentTypes,
      TextContentSlice,
      TextContentSliceDefaultPrimary,
      TextContentSliceBlockContentPrimary,
      TextContentSliceVariation,
      TextContentSliceDefault,
      TextContentSliceBlockContent,
    };
  }
}
