import type {IFilmListResponse, ITicketFilm} from "~/_utils/apiTicket";

export default defineEventHandler((event) => {
    return {
        "filmlist": [
            {
                "id_film": 8928,
                "id_ctr": 13786,
                "tx_titre_lng": "ASTOLFO",
                "tx_titre_ori": "ASTOLFO",
                "tx_comment": "<p>Astolfo, professeur &agrave; la retraite, doit quitter son appartement Romain, expuls&eacute; par la propri&eacute;taire. D&eacute;sargent&eacute;, il d&eacute;cide de retourner au village de ses anc&ecirc;tres, pour habiter le palais familial en ruine, vestige d&#145;un patrimoine que chacun tente d&#145;accaparer. Il se lie d&#145;amiti&eacute; avec le marginal qui squatte depuis des ann&eacute;es la demeure, mais aussi avec un cuisinier retrait&eacute; et un jeune sans emploi. Mais surtout, il rencontre Stefania, une femme de son &acirc;ge, timide, douce et g&eacute;n&eacute;reuse. Encourag&eacute; par ses amis, Astolfo fait un pas courageux et apprend avec joie qu&#145;il n&#145;est jamais trop tard pour tomber amoureux.</p></b></u></i>",
                "tx_duree": "1h31",
                "tx_age": "Age légal 16 ans / suggéré dès 16 ans / accompagné dès 14 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Italie",
                "tx_annee": "2023",
                "tx_realisateur": "De Gianni DI GREGORIO",
                "tx_acteur": "Avec Gianni DI GREGORIO, Stefania SANDRELLI, Mauro LAMANTIA",
                "tx_distributeur": "XENIX FILMDISTRIBUTION GMBH",
                "ur_distributeur": "http://www.xenixfilm.ch/fr",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0008928.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0008928.jpg",
                "id_vision": 2,
                "da_depart": "2024-02-28"
            },
            {
                "id_film": 9125,
                "id_ctr": 13784,
                "tx_titre_lng": "LA BETE",
                "tx_titre_ori": "LA BETE",
                "tx_comment": "<p>Dans un futur proche o&ugrave; r&egrave;gne l&#145;intelligence artificielle, les &eacute;motions humaines sont devenues une menace. Pour s&#145;en d&eacute;barrasser, Gabrielle doit purifier son ADN en replongeant dans ses vies ant&eacute;rieures. Elle y retrouve Louis, son grand amour. Mais une peur l&#145;envahit, le pressentiment qu&#145;une catastrophe se pr&eacute;pare.</p><p>S&eacute;ance en collaboration avec #cin&eacute;</p></b></u></i>",
                "tx_duree": "2h26",
                "tx_age": "Age légal 14 ans / suggéré dès 16 ans / accompagné dès 12 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "France",
                "tx_annee": "2024",
                "tx_realisateur": "De Bertrand BONELLO",
                "tx_acteur": "Avec Léa SEYDOUX, George MACKAY",
                "tx_distributeur": "SISTER DISTRIBUTION",
                "ur_distributeur": "http://sister-distribution.ch/",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009125.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009125.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-21"
            },
            {
                "id_film": 9055,
                "id_ctr": 13750,
                "tx_titre_lng": "BISONS",
                "tx_titre_ori": "BISONS",
                "tx_comment": "<p>Steve, un jeune lutteur de 26 ans, doit sauver la ferme familiale endett&eacute;e apr&egrave;s la mort de son p&egrave;re. Avec l&#145;aide de son fr&egrave;re Jo&euml;l, tout juste sorti de prison, il participe &agrave; des combats clandestins de plus en plus violents en France pour sauver le peu qu&#145;il leur reste.</p><p>6 nominations au Prix du Cin&eacute;ma Suisse - Un film percutant et attachant!</p></b></u></i>",
                "tx_duree": "1h43",
                "tx_age": "Age légal 14 ans / suggéré dès 16 ans / accompagné dès 12 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Suisse",
                "tx_annee": "2024",
                "tx_realisateur": "De Pierre MONNARD",
                "tx_acteur": "Avec Maxime VALVINI, Karim BARRAS, Marie BERTO, India HAIR",
                "tx_distributeur": "ELITE FILM AG",
                "ur_distributeur": "https://www.ascot-elite.ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009055.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009055.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-07"
            },
            {
                "id_film": 9061,
                "id_ctr": 13761,
                "tx_titre_lng": "CAPTIVES",
                "tx_titre_ori": "CAPTIVES",
                "tx_comment": "<p>Paris, 1894. Qui est Fanni qui pr&eacute;tend s&#145;&ecirc;tre laiss&eacute;e enfermer volontairement &agrave; l&#145;H&ocirc;pital de la Salp&ecirc;tri&egrave;re ? Cherchant sa m&egrave;re parmi la multitude des femmes accus&eacute;es de folie, Fanni d&eacute;couvre une r&eacute;alit&eacute; de l&#145;asile toute autre que ce qu&#145;elle imaginait, ainsi que l&#145;amiti&eacute; inattendue de compagnes d&#145;infortune. Le dernier grand bal de la Salp&ecirc;tri&egrave;re se pr&eacute;pare. Politiques, artistes, mondains s&#145;y presseront. Dernier espoir d&#145;&eacute;chapper au pi&egrave;ge qui se referme…</p></b></u></i>",
                "tx_duree": "1h50",
                "tx_age": "Age légal 14 ans / suggéré dès 16 ans / accompagné dès 12 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "France",
                "tx_annee": "2024",
                "tx_realisateur": "De Arnaud DE PALLIERES",
                "tx_acteur": "Avec Mélanie THIERRY, Marina FOÏS, Josiane BALASKO, Carole BOUQUET, Lucie ZHANG, Yolande MOREAU",
                "tx_distributeur": "CINEWORX GMBH",
                "ur_distributeur": "http://www.cineworx.ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009061.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009061.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-14"
            },
            {
                "id_film": 7422,
                "id_ctr": 13774,
                "tx_titre_lng": "COLETTE",
                "tx_titre_ori": "COLETTE",
                "tx_comment": "<p>Malgr&eacute; leurs quatorze ans d&#145;&eacute;cart, Gabrielle Sidonie Colette, jeune fille &agrave; l&#145;esprit rebelle, &eacute;pouse Willy, &eacute;crivain aussi &eacute;gocentrique que s&eacute;ducteur. Sachant rep&eacute;rer les talents mieux que quiconque, Willy autorise Colette &agrave; &eacute;crire - &agrave; condition qu&#145;il signe ses romans &agrave; sa place. Suite au triomphe de la s&eacute;rie des Claudine, Colette souffre de plus en plus de ne pas &ecirc;tre reconnue pour son &oelig;uvre... </p><p>Soir&eacute;e Cin&eacute;Zonta - Prix unique frs 35.- / d&egrave;s 19:45, ap&eacute;ro riche, suivi d&egrave;s 20:30 de la projection du film. </p><p>R&eacute;servation des billets par mail: fribourg.zonta@gmail.com</p></b></u></i>",
                "tx_duree": "1h51",
                "tx_age": "Age légal 6 ans / suggéré dès 12 ans / accompagné dès 4 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Royaume-Uni",
                "tx_annee": "2019",
                "tx_realisateur": "De Wash WESTMORELAND",
                "tx_acteur": "Avec Keira KNIGHTLEY, Dominic WEST, Eleanor TOMLINSON",
                "tx_distributeur": "DCM FILM DISTRIBUTION (SCHWEIZ) GMBH",
                "ur_distributeur": "http://www.dcmworld.com/distribution_ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0007422.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0007422.jpg",
                "id_vision": 3,
                "da_depart": "2024-02-28"
            },
            {
                "id_film": 9108,
                "id_ctr": 13768,
                "tx_titre_lng": "GADJO",
                "tx_titre_ori": "RUAECH - EINE REISE INS JENISCHE EUROPA",
                "tx_comment": "<p>Invit&eacute;e par un ami myst&eacute;rieux, une &eacute;quipe de tournage entreprend un voyage &agrave; travers une Europe y&eacute;niche cach&eacute;e, qui s&#145;&eacute;tend des faubourgs poussi&eacute;reux de Savoie aux for&ecirc;ts de Carinthie. Racont&eacute; par des voix jeunes et &acirc;g&eacute;es, un panorama kal&eacute;idoscopique de la vie y&eacute;niche se d&eacute;ploie. Un lien invisible unit ces personnes: ce sont les blessures profondes du pass&eacute;, mais aussi leur amour de la libert&eacute;.</p><p>S&eacute;ance suivie d&#145;une discussion!</p></b></u></i>",
                "tx_duree": "1h58",
                "tx_age": "Age légal 12 ans / suggéré dès 14 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Suisse",
                "tx_annee": "2024",
                "tx_realisateur": "De Andreas MULLER, Simon Guy FÄSSLER, Marcel BÄCHTIGER",
                "tx_acteur": "",
                "tx_distributeur": "FRENETIC FILMS",
                "ur_distributeur": "https://www.frenetic.ch/fr/a-laffiche/",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009108.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009108.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-21"
            },
            {
                "id_film": 9047,
                "id_ctr": 13713,
                "tx_titre_lng": "MAY DECEMBER",
                "tx_titre_ori": "MAY DECEMBER",
                "tx_comment": "<p>L&#145;actrice Elizabeth se rend sur la c&ocirc;te du Maine pour &eacute;tudier la femme qu&#145;elle doit jouer dans un film. Deux d&eacute;cennies plus t&ocirc;t, Gracie a fait l&#145;objet d&#145;un scandale pour avoir &eacute;pous&eacute; un homme beaucoup plus jeune qu&#145;elle. Alors que Gracie et son mari se pr&eacute;parent &agrave; envoyer leurs jumeaux &agrave; l&#145;universit&eacute;, la dynamique familiale d&#145;Elizabeth commence &agrave; s&#145;effriter.</p></b></u></i>",
                "tx_duree": "1h57",
                "tx_age": "Age légal 16 ans / suggéré dès 16 ans / accompagné dès 14 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "USA",
                "tx_annee": "2024",
                "tx_realisateur": "De Todd HAYNES",
                "tx_acteur": "Avec Natalie PORTMAN, Juliane MOORE, Charles MELTON, Piper CURDA",
                "tx_distributeur": "ELITE FILM AG",
                "ur_distributeur": "https://www.ascot-elite.ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009047.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009047.jpg",
                "id_vision": 1,
                "da_depart": "2024-01-24"
            },
            {
                "id_film": 9059,
                "id_ctr": 13745,
                "tx_titre_lng": "MONSIEUR BOUT-DE-BOIS",
                "tx_titre_ori": "STICK MAN",
                "tx_comment": "<p>Monsieur Bout-de-Bois m&egrave;ne une existence paisible dans son arbre avec Madame Bout- de-Bois et leur famille. Un matin, il part pour son footing matinal. Un chien, qui le prend pour un simple b&agrave;ton, l&#145;attrape et l&#145;emporte. C&#145;est le d&eacute;but d&#145;une s&eacute;rie d&#145;aventures qui vont le mener tr&egrave;s loin de chez lui... </p><p>Pr&eacute;c&eacute;d&eacute; de petits courts m&eacute;trages.</p><p>Tarif unique frs 11.- pour toute la famille! </p></b></u></i>",
                "tx_duree": "0h48",
                "tx_age": "Pour tous",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Royaume-Uni",
                "tx_annee": "2024",
                "tx_realisateur": "De Jeroen JASPAERT, Daniel SNADDON",
                "tx_acteur": "",
                "tx_distributeur": "OUTSIDE THE BOX",
                "ur_distributeur": "https://outside-thebox.ch/",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009059.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009059.jpg",
                "id_vision": 1,
                "da_depart": "2024-01-31"
            },
            {
                "id_film": 8951,
                "id_ctr": 13588,
                "tx_titre_lng": "PERFECT DAYS",
                "tx_titre_ori": "PERFECT DAYS",
                "tx_comment": "<p>Hirayama semble totalement satisfait de sa vie simple de nettoyeur de toilettes &agrave; Tokyo. En dehors de son quotidien tr&egrave;s structur&eacute;, il aime la musique et les livres. Et il aime les arbres et les photographie. Une s&eacute;rie de rencontres inattendues r&eacute;v&egrave;le peu &agrave; peu plus de son pass&eacute;. Une r&eacute;flexion profond&eacute;ment &eacute;mouvante et po&eacute;tique sur la recherche de la beaut&eacute; dans le monde quotidien qui nous entoure.</p></b></u></i>",
                "tx_duree": "2h04",
                "tx_age": "Age légal 8 ans / suggéré dès 14 ans / accompagné dès 6 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Japon",
                "tx_annee": "2023",
                "tx_realisateur": "De Wim WENDERS",
                "tx_acteur": "Avec Yumi ASÔ, Tokio EMOTO, Sayuri ISHIKAWA",
                "tx_distributeur": "DCM FILM DISTRIBUTION (SCHWEIZ) GMBH",
                "ur_distributeur": "http://www.dcmworld.com/distribution_ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0008951.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0008951.jpg",
                "id_vision": 1,
                "da_depart": "2023-11-22"
            },
            {
                "id_film": 9038,
                "id_ctr": 13735,
                "tx_titre_lng": "RETOUR EN ALEXANDRIE",
                "tx_titre_ori": "RETOUR EN ALEXANDRIE",
                "tx_comment": "<p>Apr&egrave;s vingt ans d&#145;absence, Sue retourne en Egypte, son pays natal, pour revoir sa m&egrave;re, Fairouz, une aristocrate excentrique, avec qui elle a rompu tout lien. Ce voyage surprenant, qui la m&egrave;ne du Caire &agrave; Alexandrie, teint&eacute; de souvenirs lointains, de nostalgie et de sentiments m&ecirc;l&eacute;s &agrave; l&#145;&eacute;gard de son pass&eacute;, lui permettra de devenir libre et affranchie. </p></b></u></i>",
                "tx_duree": "1h30",
                "tx_age": "Age légal 8 ans / suggéré dès 12 ans / accompagné dès 6 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Suisse",
                "tx_annee": "2024",
                "tx_realisateur": "De Tamer RUGGLI",
                "tx_acteur": "Avec Nadine LABAKI, Fanny ARDENT",
                "tx_distributeur": "AGORA FILMS",
                "ur_distributeur": "http://www.agorafilms.net",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009038.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009038.jpg",
                "id_vision": 1,
                "da_depart": "2024-01-31"
            },
            {
                "id_film": 9130,
                "id_ctr": 13787,
                "tx_titre_lng": "LOS REYES DEL MUNDO",
                "tx_titre_ori": "LOS REYES DEL MUNDO",
                "tx_comment": "<p>Le jeune R&agrave; et ses quatre amis vivent dans les rues de Medellin. Ils n&#145;ont ni famille ni racines. Leur espoir rena&icirc;t lorsque le gouvernement promet &agrave; R&agrave; le droit de r&eacute;cup&eacute;rer la propri&eacute;t&eacute; confisqu&eacute;e &agrave; sa famille par les paramilitaires. A la recherche de cette terre promise o&ugrave; ils pourraient vivre ensemble, libres sans subir ni m&eacute;pris ni humiliations, ils quittent la ville et empruntent la route p&eacute;rilleuse de l&#145;arri&egrave;re-pays. Un voyage palpitant commence, o&ugrave; onirisme et r&eacute;alit&eacute; se confondent.</p></b></u></i>",
                "tx_duree": "1h44",
                "tx_age": "Age légal 16 ans / suggéré dès 16 ans / accompagné dès 14 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Colombie",
                "tx_annee": "2024",
                "tx_realisateur": "De Laura MORA",
                "tx_acteur": "Avec Carlos Andres CASATANEDA, Brahian Stiven ACEVEDO, Davidson Andrés FLORES, Cristian David CAMPANA",
                "tx_distributeur": "XENIX FILMDISTRIBUTION GMBH",
                "ur_distributeur": "http://www.xenixfilm.ch/fr",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009130.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009130.jpg",
                "id_vision": 2,
                "da_depart": "2024-02-28"
            },
            {
                "id_film": 9139,
                "id_ctr": 13785,
                "tx_titre_lng": "RISE FESTIVAL FRIBOURG 2024",
                "tx_titre_ori": "RISE FESTIVAL FRIBOURG 2024",
                "tx_comment": "<p>Le &quot;Rise festival&quot; est de retour &agrave; Fribourg. Deux heures de projection de courts m&eacute;trages halieutiques in&eacute;dits attendent les spectateurs p&ecirc;cheurs ou non. Tourn&eacute;s en France ou &agrave; l&#145;&eacute;tranger, les films v&eacute;hiculent ces m&ecirc;mes valeurs qui fondent le Rise Festival depuis ses d&eacute;buts: la magie d&#145;un gobage, la beaut&eacute; des rivi&egrave;res, le respect de la nature, l&#145;&eacute;motion partag&eacute;e autour de la pratique de la p&ecirc;che &agrave; la mouche. A c&ocirc;t&eacute; de la promotion de destinations halieutiques exotiques, le Rise Festival s&#145;emploie aussi &agrave; d&eacute;montrer la r&eacute;silience de nos biotopes et leur int&eacute;r&ecirc;t piscicole lorsque ceux-ci sont bien g&eacute;r&eacute;s. </p></b></u></i>",
                "tx_duree": "2h00",
                "tx_age": "Age légal 12 ans / suggéré dès 12 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Autres",
                "tx_annee": "2024",
                "tx_realisateur": "De  divers cinéastes",
                "tx_acteur": "",
                "tx_distributeur": "DIVERS",
                "ur_distributeur": "",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009139.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009139.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-28"
            },
            {
                "id_film": 9020,
                "id_ctr": 13752,
                "tx_titre_lng": "RIVIERE",
                "tx_titre_ori": "RIVIERE",
                "tx_comment": "<p>En fugue &agrave; 17 ans, Manon quitte les montagnes suisses &agrave; la recherche de son p&egrave;re, qui reste introuvable. A la d&eacute;couverte de nouveaux liens et de son premier amour, elle s&#145;efforce de suivre la voie qu&#145;elle avait trac&eacute;e sur la glace: devenir hockeyeuse professionnelle.</p><p>Projection suivie d&#145;une discussion avec l&#145;&eacute;quipe du film!</p></b></u></i>",
                "tx_duree": "1h45",
                "tx_age": "Age légal 12 ans / suggéré dès 14 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Suisse",
                "tx_annee": "2024",
                "tx_realisateur": "De Hugues HARICHE",
                "tx_acteur": "Avec Flavie DELANGLE, Sarah BRAMMS, Camille RUTHEFORD",
                "tx_distributeur": "OUTSIDE THE BOX",
                "ur_distributeur": "https://outside-thebox.ch/",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009020.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009020.jpg",
                "id_vision": 11,
                "da_depart": "2024-02-21"
            },
            {
                "id_film": 9060,
                "id_ctr": 13744,
                "tx_titre_lng": "LA SALLE DES PROFS",
                "tx_titre_ori": "DAS LEHRERZIMMER",
                "tx_comment": "<p>Carla Nowak commence son premier poste d&#145;enseignante de math&eacute;matiques et de sport dans un gymnase. Elle fait son travail avec enthousiasme et son id&eacute;alisme sans limite fait parfois froncer les sourcils de ses coll&egrave;gues qui imposent leur politique de z&eacute;ro tol&eacute;rance avec fermet&eacute;. Quand plusieurs vols sont constat&eacute;s dans l&#145;&eacute;cole et que les soup&ccedil;ons portent sur l&#145;un de ses &eacute;l&egrave;ves, Carla m&egrave;ne sa propre enqu&ecirc;te ce qui provoque un v&eacute;ritable toll&eacute;. Les &eacute;v&eacute;nements s&#145;enchainent et la jeune enseignante se retrouve m&eacute;diatrice entre parents indign&eacute;s, coll&egrave;gues autoritaires et jeunes agressifs. Elle tente d&#145;enrayer l&#145;escalade avec de l&#145;impartialit&eacute; et des &eacute;changes ouverts, mais la dynamique cr&eacute;&eacute;e devient hors de contr&ocirc;le.</p></b></u></i>",
                "tx_duree": "1h39",
                "tx_age": "Age légal 12 ans / suggéré dès 12 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Allemagne",
                "tx_annee": "2024",
                "tx_realisateur": "De Ilker CATAK",
                "tx_acteur": "Avec Leonie BENESCH, Michael KLAMMER, Rafael STACHOWIAK, Anne-Kathrin GUMMICH",
                "tx_distributeur": "FILMCOOPI ZÜRICH AG",
                "ur_distributeur": "http://www.filmcoopi.ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009060.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009060.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-07"
            },
            {
                "id_film": 9058,
                "id_ctr": 13756,
                "tx_titre_lng": "SOUS LE VENT DES MARQUISES",
                "tx_titre_ori": "SOUS LE VENT DES MARQUISES",
                "tx_comment": "<p>Quand Alain doit jouer Brel, son destin se m&eacute;lange &agrave; celui de l&#145;artiste. Cette rencontre va le rapprocher de sa fille, et bouleverser sa vie.</p></b></u></i>",
                "tx_duree": "1h31",
                "tx_age": "Age légal 12 ans / suggéré dès 14 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "France",
                "tx_annee": "2024",
                "tx_realisateur": "De Pierre GODEAU",
                "tx_acteur": "Avec François DAMIENS, Salomé DEWAELS",
                "tx_distributeur": "J.M.H. DISTRIBUTION S.A.",
                "ur_distributeur": "http://jmhsa.ch/",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009058.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009058.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-07"
            },
            {
                "id_film": 9127,
                "id_ctr": 13763,
                "tx_titre_lng": "LES SPLENDEURS D'ITALIE",
                "tx_titre_ori": "LES SPLENDEURS D'ITALIE",
                "tx_comment": "<p>Du golfe de G&ecirc;nes en passant par la Toscane jusqu&#145;en Campanie, trois r&eacute;gions d&#145;Italie offrent des sites historiques et naturels fascinants: comme entre autres, la tr&egrave;s spectaculaire c&ocirc;te Amalfitaine, le resplendissant parc naturel des Cinq terre, la Toscane berceau de la renaissance ou les impressionnantes fouilles de Pomp&eacute;i... V&eacute;ritable ode &agrave; la beaut&eacute;, cette immersion dans l&#145;Italie des splendeurs, nous entra&icirc;ne dans un vertige &eacute;motionnel toujours passionnant.</p></b></u></i>",
                "tx_duree": "1h30",
                "tx_age": "Age légal 6 ans / suggéré dès 10 ans / accompagné dès 4 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Italie",
                "tx_annee": "2024",
                "tx_realisateur": "De Mario INTROIA",
                "tx_acteur": "",
                "tx_distributeur": "CINE EVENTS SARL",
                "ur_distributeur": "www.capsurlemonde.ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009127.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009127.jpg",
                "id_vision": 1,
                "da_depart": "2024-02-14"
            },
            {
                "id_film": 9010,
                "id_ctr": 13593,
                "tx_titre_lng": "LA TRESSE",
                "tx_titre_ori": "LA TRESSE",
                "tx_comment": "<p>Inde. Smita est une Intouchable. Elle r&ecirc;ve de voir sa fille &eacute;chapper &agrave; sa condition mis&eacute;rable et entrer &agrave; l&#145;&eacute;cole. Italie. Giulia travaille dans l&#145;atelier de son p&egrave;re. Lorsqu&#145;il est victime d&#145;un accident, elle d&eacute;couvre que l&#145;entreprise familiale est ruin&eacute;e. Canada. Sarah, avocate r&eacute;put&eacute;e, va &ecirc;tre promue &agrave; la t&ecirc;te de son cabinet quand elle apprend qu&#145;elle est malade. Trois vies, trois femmes, trois continents. Trois combats &agrave; mener. Si elles ne se connaissent pas, Smita, Giulia et Sarah sont li&eacute;es sans le savoir par ce qu&#145;elles ont de plus intime et de plus singulier.</p><p>D&#145;apr&egrave;s le best-seller de Laetitia Colombani! </p></b></u></i>",
                "tx_duree": "2h01",
                "tx_age": "Age légal 12 ans / suggéré dès 12 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "France",
                "tx_annee": "2023",
                "tx_realisateur": "De Laetitia COLOMBANI",
                "tx_acteur": "Avec Kim RAVER, Fotini PELUSO, Mia MAELZER",
                "tx_distributeur": "PRAESENS FILM AG",
                "ur_distributeur": "http://www.praesens.com",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009010.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009010.jpg",
                "id_vision": 1,
                "da_depart": "2023-11-29"
            },
            {
                "id_film": 8988,
                "id_ctr": 13722,
                "tx_titre_lng": "VIVRE AVEC LES LOUPS",
                "tx_titre_ori": "VIVRE AVEC LES LOUPS",
                "tx_comment": "<p>Le r&eacute;alisateur nous parle du loup d&#145;une mani&egrave;re totalement nouvelle et inattendue. Il y aura bient&ocirc;t des loups un peu partout en France. Il faut donc apprendre &agrave; vivre avec les loups. D&eacute;passant les postures pol&eacute;miques, l&#145;auteur nous am&egrave;ne de mani&egrave;re sensible et cin&eacute;matographique &agrave; percevoir diff&eacute;remment la nature qui nous entoure et les animaux qui l&#145;habitent: chevreuils, chamois, bouquetins...</p><p>Un film qui apporte une contribution essentielle au d&eacute;bat actuel sur le loup en Suisse et en Europe.</p></b></u></i>",
                "tx_duree": "1h29",
                "tx_age": "Age légal 6 ans / suggéré dès 10 ans / accompagné dès 4 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "France",
                "tx_annee": "2024",
                "tx_realisateur": "De Jean-Michel BERTRAND",
                "tx_acteur": "Avec Jean-Michel BERTRAND,  des animaux et des êtres humains",
                "tx_distributeur": "J.M.H. DISTRIBUTION S.A.",
                "ur_distributeur": "http://jmhsa.ch/",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0008988.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0008988.jpg",
                "id_vision": 1,
                "da_depart": "2024-01-24"
            },
            {
                "id_film": 9122,
                "id_ctr": 13762,
                "tx_titre_lng": "THE WONDER WAY",
                "tx_titre_ori": "THE WONDER WAY",
                "tx_comment": "<p>Comment se cr&eacute;er un monde &agrave; soi? Repousser les limites de son imagination? THE WONDER WAY est une exploration &agrave; la recherche de territoires extraordinaires, paradis terrestres ou c&eacute;lestes, fascinants et in&eacute;dits. Un voyage hors du temps, &agrave; la rencontre de ceux qui imaginent d&#145;autres mondes dans ce monde. De la fantasmagorie de Randlett King Lawrence &agrave; la sculpture astrale STAR AXIS de Charles Ross, en passant par les cartes de Jugnet+Clairet, le Mus&eacute;e du D&eacute;sert de Noah Purifoy, le Jardin d&#145;Eden de Jean Wisniewski ou la premi&egrave;re exoplan&egrave;te de Didier Queloz, d&eacute;couvrez des univers surprenants...</p><p>S&eacute;ance suivie d&#145;une rencontre avec la r&eacute;alisatrice! </p></b></u></i>",
                "tx_duree": "1h35",
                "tx_age": "Age légal 16 ans / suggéré dès 16 ans / accompagné dès 14 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "Suisse",
                "tx_annee": "2024",
                "tx_realisateur": "De Emanuelle ANTILLE",
                "tx_acteur": "",
                "tx_distributeur": "INTERMEZZO FILMS SA",
                "ur_distributeur": "",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009122.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009122.jpg",
                "id_vision": 11,
                "da_depart": "2024-02-28"
            },
            {
                "id_film": 9051,
                "id_ctr": 13717,
                "tx_titre_lng": "LA ZONE D'INTERET",
                "tx_titre_ori": "THE ZONE OF INTEREST",
                "tx_comment": "<p>Le commandant d&#145;Auschwitz, Rudolf H&ouml;ss, et sa femme Hedwig s&#145;efforcent de construire une vie de r&ecirc;ve pour leur famille dans un pavillon avec jardin &agrave; c&ocirc;t&eacute; du camp de concentration...</p><p>Inspir&eacute; du roman &eacute;ponyme de Martin Amis - Grand Prix du Jury &amp; le Prix de la critique internationale Cannes 2023.</p></b></u></i>",
                "tx_duree": "1h45",
                "tx_age": "Age légal 12 ans / suggéré dès 14 ans / accompagné dès 10 ans",
                "ur_age": "http://www.filmages.ch/",
                "tx_pays": "USA",
                "tx_annee": "2024",
                "tx_realisateur": "De Jonathan GLAZER",
                "tx_acteur": "Avec Sandra HUELLER, Christian FRIEDEL, Ralph HERFORTH, Maximilian BECK",
                "tx_distributeur": "FILMCOOPI ZÜRICH AG",
                "ur_distributeur": "http://www.filmcoopi.ch",
                "nb_note": 4,
                "ur_vignette": "https://cinemotion.ch/image/FV0009051.jpg",
                "ur_affiche": "https://cinemotion.ch/image/FA0009051.jpg",
                "id_vision": 1,
                "da_depart": "2024-01-31"
            }
        ]
    } as IFilmListResponse })
